### ISSUE TITLE
Are the 5 computing nodes of this project simulated by the CORE Network Simulator or by 5 virtual machines?

### ISSUE THREAD

**Issue by luotong1997** [teluashish/distributed-inference#1]
Hi!
Are the 5 computing nodes of this project simulated by the CORE Network Simulator or by 5 virtual machines? I am very confused when reproducing, can you help me answer it?

I would greatly appreciate it if you could provide an answer. Thank you very much.

**Comment by teluashish** [comment]
The compute nodes are simulated using the CORE Network Emulator @luotong1997
